package assetLists

import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import akka.util.duration._
import assertions._
import Headers._

object GetListApp {

  val scn = scenario("get app List")
    .exec(http("login")
         .get("/tdstm/auth/login")
         .check(status.is(200))
         .check(regex("""<title>Login</title>"""))
     )
    .pause(266 milliseconds)
    .exec(http("build.txt")
         .get("/tdstm/build.txt")
         .queryParam("""PRX9""", """""")
         .check(status.is(404))
         .check(regex("""<title>Apache Tomcat/6.0-snapshot - Error report</title>"""))
     )
    .pause(5)
    .feed(csv("user_tds.csv"))
    .exec(http("SingIn")
          .post("/tdstm/auth/signIn")
          .headers(headers_3)
            .param("""targetUri""", """""")
            .param("""username""", "${username}")
            .param("""password""", "${password}")
            .check(status.is(200))
            .check(regex("""<title>Project Details</title>"""))
      )
    .pause(2)
    .exec(http("userLogin updateLastPageLoad")
          .post("/tdstm/userLogin/updateLastPageLoad")
          .headers(headers_4)
          .param("""url""", """/tdstm/project/show""")
          .check(status.is(200))  
          .check(bodyString.is("SUCCESS"))
      )
    .pause(8)
    .exec(http("application/list")
          .get("/tdstm/application/list")
          .check(status.is(200))
          .check(regex("""<title>Application list</title>"""))
      )
    .pause(961 milliseconds)
    .exec(http("updateLastPageLoad_2")
          .post("/tdstm/userLogin/updateLastPageLoad")
          .headers(headers_4)
          .param("""url""", """/tdstm/application/list""")
          .check(status.is(200))
          .check(bodyString.is("SUCCESS"))
      )
    .pause(194 milliseconds)
    .exec(http("application/listJson")
          .get("/tdstm/application/listJson")
          .headers(headers_7)
          .queryParam("""assetName""", """""")
          .queryParam("""validation""", """""")
          .queryParam("""moveBundle""", """""")
          .queryParam("""latencys""", """""")
          .queryParam("""runbook""", """""")
          .queryParam("""sidx""", """assetName""")
          .queryParam("""validationFilter""", """""")
          .queryParam("""rows""", """100""")
          .queryParam("""sord""", """asc""")
          .queryParam("""moveBundleId""", """""")
          .queryParam("""plannedStatus""", """""")
          .queryParam("""page""", """1""")
          .queryParam("""nd""", """1399906539610""")
          .queryParam("""event""", """""")
          .queryParam("""planStatus""", """""")
          .queryParam("""filter""", """""")
          .queryParam("""_search""", """false""")
          .queryParam("""sme""", """""")
          .queryParam("""toValidate""", """""")
          .check(status.is(200))
         // .check(bodyString.is("""{"rows":[{"cell":["","AGPM","Mike Mason","BundleReady","Assigned","M1","issue","Application",348],"id":114053},{"cell":["","BlackBerry Enterprise Server","Mike Mason","BundleReady","Unassigned","Master Bundle","blank","Application",null],"id":114054},{"cell":["","BlackBerry Enterprise Server Test","Mike Mason","DependencyReview","Unassigned","Master Bundle","blank","Application",null],"id":114055},{"cell":["","BlackBerry Express","Mike Mason","DependencyReview","Assigned","M2","issue","Application",349],"id":114056},{"cell":["","Bugzilla","Bob Barker","BundleReady","Assigned","M1","issue","Application",348],"id":114057},{"cell":["","Business Objects Enterprise","Mike Mason","DependencyReview","Assigned","M2","issue","Application",349],"id":114058},{"cell":["","Business Objects Sandbox App Server DEV","Tim Burnes","DependencyReview","Assigned","M2","issue","Application",349],"id":114059},{"cell":["","Business Objects Sandbox Web Server DEV","Tim Burnes","DependencyReview","Assigned","M2","issue","Application",349],"id":114060},{"cell":["","Citrix","Bob Barker","BundleReady","Unassigned","M3","blank","Application",350],"id":114061},{"cell":["","DHCP","Bob Barker","BundleReady","Assigned","M1","issue","Application",348],"id":114062},{"cell":["","DNS","Bob Barker","BundleReady","Assigned","M1","issue","Application",348],"id":114063},{"cell":["","Domain Controller","Regis Philbin","DependencyReview","Assigned","M1","issue","Application",348],"id":114064},{"cell":["","Eclipser","Regis Philbin","Validated","Assigned","M2","issue","Application",349],"id":114066},{"cell":["","Employee Portal","Tom Smith","DependencyReview","Assigned","M2","issue","Application",349],"id":114067},{"cell":["","Employee Portal DEV/TST/UAT","Tom Smith","Discovery","Unassigned","M1","issue","Application",348],"id":114068},{"cell":["","Enterprise Reporting","Tom Smith","DependencyReview","Assigned","M2","issue","Application",349],"id":114069},{"cell":["","ESX virtualization host","Tom Jenkins","DependencyReview","Assigned","M2","issue","Application",349],"id":114070},{"cell":["","Exchange 2010","Tom Jenkins","DependencyReview","Assigned","M1","issue","Application",348],"id":114071},{"cell":["","Exchange 2013 Test","Tom Jenkins","DependencyReview","Assigned","M1","issue","Application",348],"id":114072},{"cell":["","External DNS server","Tom Jenkins","DependencyReview","Assigned","M1","issue","Application",348],"id":114073},{"cell":["","Intellex Video Monitoring","Han Solo","Discovery","Unassigned","Master Bundle","blank","Application",null],"id":122722},{"cell":["","Marketo","Regis Philbin","BundleReady","Unassigned","M1","issue","Application",348],"id":114076},{"cell":["","MS SQL Server - DEV","Clark Kent","Discovery","Assigned","M1","issue","Application",348],"id":114100},{"cell":["","MSSQL Cluster PROD","Clark Kent","Validated","Confirmed","Not Moving","blank","Application",null],"id":123567},{"cell":["","MSSQL Cluster PROD TX","Clark Kent","DependencyReview","Confirmed","Buildout","blank","Application",364],"id":114101},{"cell":["","MySQL database server","Homer Simpson","DependencyReview","Assigned","M1","issue","Application",348],"id":114077},{"cell":["","MySQL DEV","Homer Simpson","Discovery","Assigned","M1","issue","Application",348],"id":114078},{"cell":["","MySQL Enterprise Monitor","Homer Simpson","DependencyReview","Assigned","M1","issue","Application",348],"id":114079},{"cell":["","MySQL TST","Homer Simpson","Discovery","Unassigned","Master Bundle","blank","Application",null],"id":114080},{"cell":["","NetApp / DFM monitoring","Homer Simpson","DependencyReview","Assigned","M2","issue","Application",349],"id":114081},{"cell":["","NetApp Cluster 1","Homer Simpson","Discovery","Unassigned","Master Bundle","blank","Application",null],"id":122721},{"cell":["","Oracle 11i Accl","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114082},{"cell":["","Oracle 11i Accl -Dev","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114083},{"cell":["","Oracle 11i Accl -Test","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114084},{"cell":["","Oracle R12","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114086},{"cell":["","Oracle R12 -Dev","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114087},{"cell":["","Oracle R12 -Test","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114088},{"cell":["","PeopleSoft","Kim Thompson","BundleReady","Assigned","M2","issue","Application",349],"id":114089},{"cell":["","PeopleSoft DEV","Tom Jenkins","DependencyReview","Assigned","M2","issue","Application",349],"id":114090},{"cell":["","PeopleSoft HR Process Server","Erin Lopez","DependencyReview","Assigned","M2","issue","Application",349],"id":114091},{"cell":["","Puppet","Erin Lopez","DependencyReview","Unassigned","Master Bundle","blank","Application",null],"id":114092},{"cell":["","Puppet DEV","Erin Lopez","DependencyReview","Assigned","M1","issue","Application",348],"id":114093},{"cell":["","Secondary external DNS server","Erin Lopez","DependencyReview","Unassigned","Master Bundle","blank","Application",null],"id":114094},{"cell":["","SharePoint 2007 DEV","Chris Picard","Validated","Assigned","M1","issue","Application",348],"id":114097},{"cell":["","SharePoint 2007 PROD","Chris Picard","BundleReady","Assigned","M2","issue","Application",349],"id":114096},{"cell":["","SharePoint 2007 TST","Chris Picard","Discovery","Assigned","M1","issue","Application",348],"id":114098},{"cell":["","Silktest","Paul Pierce","BundleReady","Assigned","M1","issue","Application",348],"id":114099},{"cell":["","SQL Server DEV","Clark Kent","BundleReady","Assigned","M1","issue","Application",348],"id":114102},{"cell":["","SQL Server TST","Clark Kent","Discovery","Unassigned","Master Bundle","blank","Application",null],"id":114104},{"cell":["","SubVersion (Code repository)","Steve Pritchard","DependencyReview","Assigned","M2","issue","Application",349],"id":114105},{"cell":["","System Center Config Mgr","Steve Pritchard","DependencyReview","Assigned","M1","issue","Application",348],"id":114107},{"cell":["","System Center Config Mgr - Secondary Distribution Point","Steve Pritchard","Validated","Assigned","M1","issue","Application",348],"id":114108},{"cell":["","V Cluster Dev/Test","Tom Jenkins","BundleReady","Moved","Buildout","blank","Application",364],"id":114075},{"cell":["","V Cluster Prod","Tom Jenkins","BundleReady","Moved","Buildout","blank","Application",364],"id":114074},{"cell":["","vCenter - Main Farm","Paul Pierce","BundleReady","Assigned","M3","issue","Application",350],"id":114109},{"cell":["","vCloud Director","Tom Moore","BundleReady","Assigned","M2","issue","Application",349],"id":114112},{"cell":["","Visual Source Safe","Kelly Braun","DependencyReview","Assigned","M1","issue","Application",348],"id":114113},{"cell":["","VMWare Vcenter","Kelly Braun","DependencyReview","Assigned","M2","issue","Application",349],"id":114114},{"cell":["","VMWare Vcenter Test","Kelly Braun","BundleReady","Assigned","Not Moving","blank","Application",null],"id":114115}],"page":1,"records":59,"total":1}"""))
      )
    .pause(293 milliseconds)
    .exec(http("application/listJson_2")
          .get("/tdstm/application/listJson")
          .headers(headers_7)
          .queryParam("""latencys""", """""")
          .queryParam("""runbook""", """""")
          .queryParam("""sidx""", """assetName""")
          .queryParam("""validationFilter""", """""")
          .queryParam("""rows""", """100""")
          .queryParam("""moveBundleId""", """""")
          .queryParam("""sord""", """asc""")
          .queryParam("""plannedStatus""", """""")
          .queryParam("""page""", """1""")
          .queryParam("""nd""", """1399906540163""")
          .queryParam("""filter""", """""")
          .queryParam("""toValidate""", """""")
          .queryParam("""_search""", """false""")
          .check(status.is(200))
          // .check(bodyString.is("${listApp}"))
          // .check(bodyString.is("""{"rows":[{"cell":["","AGPM","Mike Mason","BundleReady","Assigned","M1","issue","Application",348],"id":114053},{"cell":["","BlackBerry Enterprise Server","Mike Mason","BundleReady","Unassigned","Master Bundle","blank","Application",null],"id":114054},{"cell":["","BlackBerry Enterprise Server Test","Mike Mason","DependencyReview","Unassigned","Master Bundle","blank","Application",null],"id":114055},{"cell":["","BlackBerry Express","Mike Mason","DependencyReview","Assigned","M2","issue","Application",349],"id":114056},{"cell":["","Bugzilla","Bob Barker","BundleReady","Assigned","M1","issue","Application",348],"id":114057},{"cell":["","Business Objects Enterprise","Mike Mason","DependencyReview","Assigned","M2","issue","Application",349],"id":114058},{"cell":["","Business Objects Sandbox App Server DEV","Tim Burnes","DependencyReview","Assigned","M2","issue","Application",349],"id":114059},{"cell":["","Business Objects Sandbox Web Server DEV","Tim Burnes","DependencyReview","Assigned","M2","issue","Application",349],"id":114060},{"cell":["","Citrix","Bob Barker","BundleReady","Unassigned","M3","blank","Application",350],"id":114061},{"cell":["","DHCP","Bob Barker","BundleReady","Assigned","M1","issue","Application",348],"id":114062},{"cell":["","DNS","Bob Barker","BundleReady","Assigned","M1","issue","Application",348],"id":114063},{"cell":["","Domain Controller","Regis Philbin","DependencyReview","Assigned","M1","issue","Application",348],"id":114064},{"cell":["","Eclipser","Regis Philbin","Validated","Assigned","M2","issue","Application",349],"id":114066},{"cell":["","Employee Portal","Tom Smith","DependencyReview","Assigned","M2","issue","Application",349],"id":114067},{"cell":["","Employee Portal DEV/TST/UAT","Tom Smith","Discovery","Unassigned","M1","issue","Application",348],"id":114068},{"cell":["","Enterprise Reporting","Tom Smith","DependencyReview","Assigned","M2","issue","Application",349],"id":114069},{"cell":["","ESX virtualization host","Tom Jenkins","DependencyReview","Assigned","M2","issue","Application",349],"id":114070},{"cell":["","Exchange 2010","Tom Jenkins","DependencyReview","Assigned","M1","issue","Application",348],"id":114071},{"cell":["","Exchange 2013 Test","Tom Jenkins","DependencyReview","Assigned","M1","issue","Application",348],"id":114072},{"cell":["","External DNS server","Tom Jenkins","DependencyReview","Assigned","M1","issue","Application",348],"id":114073},{"cell":["","Intellex Video Monitoring","Han Solo","Discovery","Unassigned","Master Bundle","blank","Application",null],"id":122722},{"cell":["","Marketo","Regis Philbin","BundleReady","Unassigned","M1","issue","Application",348],"id":114076},{"cell":["","MS SQL Server - DEV","Clark Kent","Discovery","Assigned","M1","issue","Application",348],"id":114100},{"cell":["","MSSQL Cluster PROD","Clark Kent","Validated","Confirmed","Not Moving","blank","Application",null],"id":123567},{"cell":["","MSSQL Cluster PROD TX","Clark Kent","DependencyReview","Confirmed","Buildout","blank","Application",364],"id":114101},{"cell":["","MySQL database server","Homer Simpson","DependencyReview","Assigned","M1","issue","Application",348],"id":114077},{"cell":["","MySQL DEV","Homer Simpson","Discovery","Assigned","M1","issue","Application",348],"id":114078},{"cell":["","MySQL Enterprise Monitor","Homer Simpson","DependencyReview","Assigned","M1","issue","Application",348],"id":114079},{"cell":["","MySQL TST","Homer Simpson","Discovery","Unassigned","Master Bundle","blank","Application",null],"id":114080},{"cell":["","NetApp / DFM monitoring","Homer Simpson","DependencyReview","Assigned","M2","issue","Application",349],"id":114081},{"cell":["","NetApp Cluster 1","Homer Simpson","Discovery","Unassigned","Master Bundle","blank","Application",null],"id":122721},{"cell":["","Oracle 11i Accl","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114082},{"cell":["","Oracle 11i Accl -Dev","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114083},{"cell":["","Oracle 11i Accl -Test","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114084},{"cell":["","Oracle R12","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114086},{"cell":["","Oracle R12 -Dev","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114087},{"cell":["","Oracle R12 -Test","Johnny Depp","BundleReady","Assigned","M2","issue","Application",349],"id":114088},{"cell":["","PeopleSoft","Kim Thompson","BundleReady","Assigned","M2","issue","Application",349],"id":114089},{"cell":["","PeopleSoft DEV","Tom Jenkins","DependencyReview","Assigned","M2","issue","Application",349],"id":114090},{"cell":["","PeopleSoft HR Process Server","Erin Lopez","DependencyReview","Assigned","M2","issue","Application",349],"id":114091},{"cell":["","Puppet","Erin Lopez","DependencyReview","Unassigned","Master Bundle","blank","Application",null],"id":114092},{"cell":["","Puppet DEV","Erin Lopez","DependencyReview","Assigned","M1","issue","Application",348],"id":114093},{"cell":["","Secondary external DNS server","Erin Lopez","DependencyReview","Unassigned","Master Bundle","blank","Application",null],"id":114094},{"cell":["","SharePoint 2007 DEV","Chris Picard","Validated","Assigned","M1","issue","Application",348],"id":114097},{"cell":["","SharePoint 2007 PROD","Chris Picard","BundleReady","Assigned","M2","issue","Application",349],"id":114096},{"cell":["","SharePoint 2007 TST","Chris Picard","Discovery","Assigned","M1","issue","Application",348],"id":114098},{"cell":["","Silktest","Paul Pierce","BundleReady","Assigned","M1","issue","Application",348],"id":114099},{"cell":["","SQL Server DEV","Clark Kent","BundleReady","Assigned","M1","issue","Application",348],"id":114102},{"cell":["","SQL Server TST","Clark Kent","Discovery","Unassigned","Master Bundle","blank","Application",null],"id":114104},{"cell":["","SubVersion (Code repository)","Steve Pritchard","DependencyReview","Assigned","M2","issue","Application",349],"id":114105},{"cell":["","System Center Config Mgr","Steve Pritchard","DependencyReview","Assigned","M1","issue","Application",348],"id":114107},{"cell":["","System Center Config Mgr - Secondary Distribution Point","Steve Pritchard","Validated","Assigned","M1","issue","Application",348],"id":114108},{"cell":["","V Cluster Dev/Test","Tom Jenkins","BundleReady","Moved","Buildout","blank","Application",364],"id":114075},{"cell":["","V Cluster Prod","Tom Jenkins","BundleReady","Moved","Buildout","blank","Application",364],"id":114074},{"cell":["","vCenter - Main Farm","Paul Pierce","BundleReady","Assigned","M3","issue","Application",350],"id":114109},{"cell":["","vCloud Director","Tom Moore","BundleReady","Assigned","M2","issue","Application",349],"id":114112},{"cell":["","Visual Source Safe","Kelly Braun","DependencyReview","Assigned","M1","issue","Application",348],"id":114113},{"cell":["","VMWare Vcenter","Kelly Braun","DependencyReview","Assigned","M2","issue","Application",349],"id":114114},{"cell":["","VMWare Vcenter Test","Kelly Braun","BundleReady","Assigned","Not Moving","blank","Application",null],"id":114115}],"page":1,"records":59,"total":1}"""))
      )
    .pause(10)
    .exec(http("singOut")
          .get("/tdstm/auth/signOut")
          .check(status.is(200))
          .check(regex("""<title>Login</title>"""))
      )
    .pause(212 milliseconds)
    .exec(http("build.txt_2")
          .get("/tdstm/build.txt")
          .queryParam("""mQT4""", """""")
          .check(status.is(404))
          .check(regex("""<title>Apache Tomcat/6.0-snapshot - Error report</title>"""))
      )
}