package assetLists

import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import akka.util.duration._
import assertions._
import Headers._

object GetListStorages {

  val scn = scenario("Get List Storage")
    
    .exec(http("login")
          .get("/tdstm/auth/login")
          .check(status.is(200))
          .check(regex("""<title>Login</title>"""))
      )
    .pause(102 milliseconds)
    .exec(http("build.txt")
          .get("/tdstm/build.txt")
          .queryParam("""aTJf""", """""")
          .check(status.is(404))
          .check(regex("""<title>Apache Tomcat/6.0-snapshot - Error report</title>"""))
      )
    .pause(7)  
    .feed(csv("user_tds.csv"))
    .exec(http("signIn")
          .post("/tdstm/auth/signIn")
          .headers(headers_3)
            .param("""targetUri""", """""")
            .param("""username""", "${username}")
            .param("""password""", "${password}")
            .check(status.is(200))
            .check(regex("""<title>Project Details</title>"""))
      )
    .pause(1)
    .exec(http("userLogin updateLastPageLoad")
          .post("/tdstm/userLogin/updateLastPageLoad")
          .headers(headers_4)
          .param("""url""", """/tdstm/project/show""")
          .check(status.is(200))  
          .check(bodyString.is("SUCCESS"))
      )
    .pause(4)
    .exec(http("files index")
          .get("/tdstm/files/index")
          .check(status.is(200))
          .check(regex("""<title>Storage List</title>"""))
      )
    .pause(2)
    .exec(http("userLogin updateLastPageLoad_2")
          .post("/tdstm/userLogin/updateLastPageLoad")
          .headers(headers_4)
          .param("""url""", """/tdstm/files/list""")
          .check(status.is(200))  
          .check(bodyString.is("SUCCESS"))
      )
    .pause(81 milliseconds)
    .exec(http("files listJson")
          .get("/tdstm/files/listJson")
          .headers(headers_7)
          .queryParam("""assetName""", """""")
          .queryParam("""validation""", """""")
          .queryParam("""moveBundle""", """""")
          .queryParam("""sidx""", """assetName""")
          .queryParam("""rows""", """100""")
          .queryParam("""size""", """""")
          .queryParam("""sord""", """asc""")
          .queryParam("""moveBundleId""", """""")
          .queryParam("""plannedStatus""", """""")
          .queryParam("""page""", """1""")
          .queryParam("""event""", """""")
          .queryParam("""nd""", """1399986237476""")
          .queryParam("""planStatus""", """""")
          .queryParam("""filter""", """""")
          .queryParam("""fileFormat""", """""")
          .queryParam("""toValidate""", """""")
          .queryParam("""_search""", """false""")
          .check(status.is(200))
          // .check(bodyString.is("""{"rows":[{"cell":["","Enginereeing-Shared","Fileshare",4000,"Unassigned","Master Bundle","blank","Files"],"id":122153},{"cell":["","Finance-Shared","Fileshare",1000,"Unassigned","Master Bundle","blank","Files"],"id":122068},{"cell":["","Marketing-Shared","Fileshare",2000,"Unassigned","Master Bundle","blank","Files"],"id":122152},{"cell":["","Sales-Shared","Fileshare",4000,"Unassigned","Master Bundle","blank","Files"],"id":122154},{"cell":["","Support-Shared","Fileshare",6000,"Unassigned","Master Bundle","blank","Files"],"id":122155}],"page":1,"records":5,"total":1}"""))
      )
    .pause(4)
    .exec(http("files show")
          .post("/tdstm/files/show")
          .headers(headers_4)
          .queryParam("""id""", """122153""")
          .queryParam("""redirectTo""", """files""")
          .check(status.is(200))
          // .check(regex("""<td colspan="2"><div class="dialog"  ondblclick="editEntity('files','Storage', 122153)">"""))
      )
    .pause(485 milliseconds)
    .exec(http("getTooltips")
          .post("/tdstm/common/getTooltips")
          .headers(headers_9)
          .param("""type""", """Storage""")
          .check(status.is(200))
          // .check(bodyString.is("""{"description":null,"environment":null,"externalRefId":null,"fileFormat":null,"maintExpDate":null,"modifiedBy":null,"lastUpdated":null,"moveBundle":null,"assetName":null,"planStatus":null,"rateOfChange":null,"retireDate":null,"scale":null,"size":null,"supportType":null,"validation":null,"custom1":null,"custom2":null,"custom3":null,"custom4":null,"custom5":null,"custom6":null,"custom7":null,"custom8":null,"custom9":null,"custom10":null,"custom11":null,"custom12":null,"custom13":null,"custom14":null,"custom15":null,"custom16":null,"custom17":null,"custom18":null,"custom19":null,"custom20":null,"custom21":null,"custom22":null,"custom23":null,"custom24":null,"custom25":null,"custom26":null,"custom27":null,"custom28":null,"custom29":null,"custom30":null,"custom31":null,"custom32":null,"custom33":null,"custom34":null,"custom35":null,"custom36":null,"custom37":null,"custom38":null,"custom39":null,"custom40":null,"custom41":null,"custom42":null,"custom43":null,"custom44":null,"custom45":null,"custom46":null,"custom47":null,"custom48":null,"custom49":null,"custom50":null,"custom51":null,"custom52":null,"custom53":null,"custom54":null,"custom55":null,"custom56":null,"custom57":null,"custom58":null,"custom59":null,"custom60":null,"custom61":null,"custom62":null,"custom63":null,"custom64":null}"""))
    )
    .pause(4)
    .exec(http("signOut")
          .get("/tdstm/auth/signOut")
          .check(status.is(200))
          .check(regex("""<title>Login</title>"""))
      )
    .pause(211 milliseconds)
    .exec(http("build.txt_2")
          .get("/tdstm/build.txt")
          .queryParam("""6hSZ""", """""")
          .check(status.is(404))
          .check(regex("""<title>Apache Tomcat/6.0-snapshot - Error report</title>"""))
      )
}