package assetLists

import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import akka.util.duration._
import assertions._
import Headers._

object GetListDbs {

  val scn = scenario("Get List Dbs")
    .exec(http("login")
          .get("/tdstm/auth/login")
          .check(status.is(200))
          .check(regex("""<title>Login</title>"""))
      )
    .pause(127 milliseconds)
    .exec(http("build.txt")
          .get("/tdstm/build.txt")
          .queryParam("""9GJF""", """""")
          .check(status.is(404))
          .check(regex("""<title>Apache Tomcat/6.0-snapshot - Error report</title>"""))
      )
    .pause(6)
    .feed(csv("user_tds.csv"))
    .exec(http("signIn")
          .post("/tdstm/auth/signIn")
          .headers(headers_3)
            .param("""targetUri""", """""")
            .param("""username""", "${username}")
            .param("""password""", "${password}")
            .check(status.is(200))
            .check(regex("""<title>Project Details</title>"""))
      )
    .pause(1)
    .exec(http("userLogin updateLastPageLoad")
          .post("/tdstm/userLogin/updateLastPageLoad")
          .headers(headers_4)
          .param("""url""", """/tdstm/project/show""")
          .check(status.is(200))  
          .check(bodyString.is("SUCCESS"))
      )
    .pause(4)
    .exec(http("database index")
          .get("/tdstm/database/index")
          .check(status.is(200))
          .check(regex("""<title>DB list</title>"""))
      )
    .pause(2)
    .exec(http("userLogin updateLastPageLoad_2")
          .post("/tdstm/userLogin/updateLastPageLoad")
          .headers(headers_4)
          .param("""url""", """/tdstm/database/list""")
          .check(status.is(200))  
          .check(bodyString.is("SUCCESS"))
      )
    .pause(38 milliseconds)
    .exec(http("database listJson")
          .get("/tdstm/database/listJson")
          .headers(headers_7)
          .queryParam("""assetName""", """""")
          .queryParam("""validation""", """""")
          .queryParam("""moveBundle""", """""")
          .queryParam("""sidx""", """assetName""")
          .queryParam("""rows""", """100""")
          .queryParam("""dbFormat""", """""")
          .queryParam("""sord""", """asc""")
          .queryParam("""moveBundleId""", """""")
          .queryParam("""plannedStatus""", """""")
          .queryParam("""page""", """1""")
          .queryParam("""event""", """""")
          .queryParam("""nd""", """1399986194284""")
          .queryParam("""planStatus""", """""")
          .queryParam("""filter""", """""")
          .queryParam("""toValidate""", """""")
          .queryParam("""_search""", """false""")
          .check(status.is(200))
          // .check(bodyString.is("""{"rows":[{"cell":["","Bugzilla","MySQL",500,"Unassigned","M1","blank","Database"],"id":123563},{"cell":["","Exchange-PROD","MSSQL",1780,"Unassigned","M1","issue","Database"],"id":123564},{"cell":["","FIN-PROD","Oracle",1,"Assigned","M2","blank","Database"],"id":114116},{"cell":["","HR-PROD","Oracle",1,"Assigned","M2","blank","Database"],"id":114117},{"cell":["","OEM-PROD","Oracle",1,"Unassigned","M2","blank","Database"],"id":114121},{"cell":["","PORTAL-PROD","Oracle",1,"Assigned","M2","blank","Database"],"id":114118},{"cell":["","Sharepoint-PROD","MSSQL",100,"Assigned","M1","issue","Database"],"id":122760},{"cell":["","SourceSafe-PROD","MSSQL",200,"Unassigned","M1","issue","Database"],"id":123568},{"cell":["","VMWareUpdateManager","MS SQL Server 2012",1,"Assigned","M2","blank","Database"],"id":114119},{"cell":["","VMwareVirtualCenter","MS SQL Server 2012",1,"Assigned","M2","blank","Database"],"id":114120}],"page":1,"records":10,"total":1}"""))

      )
    .pause(5)
    .exec(http("signOut")
          .get("/tdstm/auth/signOut")
          .check(status.is(200))
          .check(regex("""<title>Login</title>"""))
      )
    .pause(211 milliseconds)
    .exec(http("build.txt_2")
          .get("/tdstm/build.txt")
          .queryParam("""FtUe""", """""")
          .check(status.is(404))
          .check(regex("""<title>Apache Tomcat/6.0-snapshot - Error report</title>"""))
      )
}