import {
	faList,
	faLayerGroup,
	faBars,
	faServer,
	faDatabase,
	faBoxOpen,
	faCircle,
	faCog,
	faCogs,
	faSpinner,
	faSortAmountDown,
	faAdjust,
	faSyncAlt,
	faSearchPlus,
	faSearchMinus,
	faCubes,
	faSitemap,
	faListUl, faMinus, faCheck, faForward, faSignal, faStream, faUsers, faWindowClose, faFilter, faQuestion
} from '@fortawesome/free-solid-svg-icons';

export const FA_ICONS = {
	faList: faList,
	faLayerGroup: faLayerGroup,
	faBars: faBars,
	faServer: faServer,
	faDatabase: faDatabase,
	faBoxOpen: faBoxOpen,
	faCircle: faCircle,
	faCog: faCog,
	faCogs: faCogs,
	faSyncAlt: faSyncAlt,
	faSortAmountDown: faSortAmountDown,
	faAdjust: faAdjust,
	faSearchPlus: faSearchPlus,
	faSearchMinus: faSearchMinus,
	faTruck: faCubes,
	faSitemap: faSitemap,
	faListUl: faListUl,
	faMinus: faMinus,
	faCheck: faCheck,
	faForward: faForward,
	faSignal: faSignal,
	faStream: faStream,
	faUsers: faUsers,
	faWindowClose: faWindowClose,
	faFilter: faFilter,
	faQuestion: faQuestion,
};
