package version.v5_0_0

databaseChangeLog = {
    changeSet(author: 'jdanahy', id: '20200414-TM-17027') {
        comment('Update column width for dependency analyzer views')

        sql('''UPDATE `tdstm`.`dataview` SET report_schema='{"columns":[{"filter":"","edit":false,"domain":"common","property":"assetName","width":110,"label":"Name","locked":false},{"filter":"","edit":false,"domain":"common","property":"assetClass","width":110,"label":"Asset Class","locked":false},{"filter":"","edit":false,"domain":"common","property":"validation","width":110,"label":"Validation","locked":false},{"filter":"","edit":false,"domain":"common","property":"moveBundle","width":110,"label":"Bundle","locked":false},{"filter":"","edit":false,"domain":"common","property":"dependencyGroup","width":170,"label":"Dependency Group","locked":false},{"filter":"","edit":false,"domain":"common","property":"planStatus","width":110,"label":"Plan Status","locked":false},{"filter":"","edit":false,"domain":"common","property":"tbd","width":110,"label":"TBD","locked":false},{"filter":"","edit":false,"domain":"common","property":"conflict","width":110,"label":"Conflict","locked":false}],"domains":["common","application","database","device","storage"],"sort":{"domain":"common","property":"assetName","order":"a"}}' WHERE name='Dependency Analyzer All' ''')
        sql('''UPDATE `tdstm`.`dataview` SET report_schema='{"columns":[{"filter":"","edit":false,"domain":"common","property":"assetName","width":110,"label":"Name","locked":false},{"filter":"","edit":false,"domain":"device","property":"model","width":110,"label":"Model","locked":false},{"filter":"","edit":false,"domain":"device","property":"locationSource","width":110,"label":"Source Location","locked":false},{"filter":"","edit":false,"domain":"device","property":"roomSource","width":110,"label":"Source Room","locked":false},{"filter":"","edit":false,"domain":"device","property":"rackSource","width":110,"label":"Source Rack","locked":false},{"filter":"","edit":false,"domain":"device","property":"locationTarget","width":110,"label":"Target Location","locked":false},{"filter":"","edit":false,"domain":"device","property":"roomTarget","width":110,"label":"Target Room","locked":false},{"filter":"","edit":false,"domain":"device","property":"rackTarget","width":110,"label":"Target Rack","locked":false},{"filter":"","edit":false,"domain":"common","property":"validation","width":110,"label":"Validation","locked":false},{"filter":"","edit":false,"domain":"common","property":"moveBundle","width":110,"label":"Bundle","locked":false},{"filter":"","edit":false,"domain":"common","property":"dependencyGroup","width":170,"label":"Dependency Group","locked":false},{"filter":"","edit":false,"domain":"common","property":"planStatus","width":110,"label":"Plan Status","locked":false},{"filter":"","edit":false,"domain":"common","property":"tbd","width":110,"label":"TBD","locked":false},{"filter":"","edit":false,"domain":"common","property":"conflict","width":110,"label":"Conflict","locked":false}],"domains":["common","device"],"sort":{"domain":"common","property":"assetName","order":"a"}}' WHERE name='Dependency Analyzer Servers' ''')
        sql('''UPDATE `tdstm`.`dataview` SET report_schema='{"columns":[{"filter":"","edit":false,"domain":"common","property":"assetName","width":110,"label":"Name","locked":false},{"filter":"","edit":false,"domain":"application","property":"sme","width":110,"label":"SME1","locked":false},{"filter":"","edit":false,"domain":"application","property":"sme2","width":110,"label":"SME2","locked":false},{"filter":"","edit":false,"domain":"common","property":"validation","width":110,"label":"Validation","locked":false},{"filter":"","edit":false,"domain":"common","property":"moveBundle","width":110,"label":"Bundle","locked":false},{"filter":"","edit":false,"domain":"common","property":"dependencyGroup","width":170,"label":"Dependency Group","locked":false},{"filter":"","edit":false,"domain":"common","property":"planStatus","width":110,"label":"Plan Status","locked":false},{"filter":"","edit":false,"domain":"common","property":"tbd","width":110,"label":"TBD","locked":false},{"filter":"","edit":false,"domain":"common","property":"conflict","width":110,"label":"Conflict","locked":false}],"domains":["common","application"],"sort":{"domain":"common","property":"assetName","order":"a"}}' WHERE name='Dependency Analyzer Apps' ''')
        sql('''UPDATE `tdstm`.`dataview` SET report_schema='{"columns":[{"filter":"","edit":false,"domain":"common","property":"assetName","width":110,"label":"Name","locked":false},{"filter":"","edit":false,"domain":"database","property":"dbFormat","width":110,"label":"Format","locked":false},{"filter":"","edit":false,"domain":"common","property":"validation","width":110,"label":"Validation","locked":false},{"filter":"","edit":false,"domain":"common","property":"moveBundle","width":110,"label":"Bundle","locked":false},{"filter":"","edit":false,"domain":"common","property":"dependencyGroup","width":170,"label":"Dependency Group","locked":false},{"filter":"","edit":false,"domain":"common","property":"planStatus","width":110,"label":"Plan Status","locked":false},{"filter":"","edit":false,"domain":"common","property":"tbd","width":110,"label":"TBD","locked":false},{"filter":"","edit":false,"domain":"common","property":"conflict","width":110,"label":"Conflict","locked":false}],"domains":["common","database"],"sort":{"domain":"common","property":"assetName","order":"a"}}' WHERE name='Dependency Analyzer Databases' ''')
        sql('''UPDATE `tdstm`.`dataview` SET report_schema='{"columns":[{" filter":"","edit":false,"domain":"common","property":"assetName","width":110,"label":"Name","locked":false},{"filter":"","edit":false,"domain":"storage","property":"fileFormat","width":110,"label":"Format","locked":false},{"filter":"","edit":false,"domain":"common","property":"assetClass","width":110,"label":"Asset Class","locked":false},{"filter":"","edit":false,"domain":"common","property":"validation","width":110,"label":"Validation","locked":false},{"filter":"","edit":false,"domain":"common","property":"moveBundle","width":110,"label":"Bundle","locked":false},{"filter":"","edit":false,"domain":"common","property":"dependencyGroup","width":170,"label":"Dependency Group","locked":false},{"filter":"","edit":false,"domain":"common","property":"planStatus","width":110,"label":"Plan Status","locked":false},{"filter":"","edit":false,"domain":"common","property":"tbd","width":110,"label":"TBD","locked":false},{"filter":"","edit":false,"domain":"common","property":"conflict","width":110,"label":"Conflict","locked":false}],"domains":["common","storage"],"sort":{"domain":"common","property":"assetName","order":"a"}}' WHERE name='Dependency Analyzer Storage' ''')
    }

}
