export const SEARCH_QUITE_PERIOD = 600;
export const LAST_VISITED_PAGE = 'LAST_VISITED_PAGE';
export const LAST_SELECTED_FOLDER = 'LAST_SELECTED_FOLDER';
export const PROMPT_DEFAULT_TITLE_KEY = 'GLOBAL.CONFIRMATION_PROMPT.CONFIRMATION_REQUIRED';
export const PROMPT_DEFAULT_MESSAGE_KEY = 'GLOBAL.CONFIRMATION_PROMPT.UNSAVED_CHANGES_MESSAGE';
export const PROMPT_DELETE_ITEM_CONFIRMATION = 'GLOBAL.CONFIRMATION_PROMPT.DELETE_ITEM_CONFIRMATION';
export const PROMPT_DELETE_ITEMS_CONFIRMATION = 'GLOBAL.CONFIRMATION_PROMPT.DELETE_ITEMS_CONFIRMATION';
export const LOADER_IDLE_PERIOD = 150;
// Pagination
export const MAX_OPTIONS = [25, 50, 100, 250, 500, 1000];
export const MAX_DEFAULT = 25;

// Intervals
export enum INTERVAL {
	SECONDS = 'Seconds',
	MINUTES = 'Minutes',
	HOURS = 'Hours'
}

export const INTERVALS = [INTERVAL.SECONDS, INTERVAL.MINUTES, INTERVAL.HOURS];

export enum KEYSTROKE {
	ENTER = 'Enter',
	TAB = 'Tab',
	SHIFT_RIGHT = 'ShiftRight',
	SHIFT_LEFT = 'ShiftLeft',
	ESCAPE = 'Escape'
};

export enum DIALOG_SIZE {
	SM = 'sm',
	MD = 'md',
	LG = 'lg',
	XLG = 'xlg',
	XXL = 'xxl'
};
export const ACTIVE_INACTIVE = ['Active', 'Inactive'];

export const ERROR_STATUS = 'error';

export enum DOMAIN {
	APPLICATION = 'APPLICATION',
	COMMON = 'COMMON',
	DATABASE = 'DATABASE',
	DEVICE = 'DEVICE',
	STORAGE = 'STORAGE',
	TASK = 'TASK'
}