package assetLists

import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import akka.util.duration._
import assertions._
import Headers._

object GetListApp {

  val scn = scenario("get app List")
    .exec(http("login")
         .get("/tdstm/auth/login")
         .check(status.is(200))
         .check(regex("""<title>Login</title>"""))
     )
    .pause(5)
    .feed(csv("user_tds.csv"))
    .exec(http("SingIn")
          .post("/tdstm/auth/signIn")
          .headers(headers_3)
            .param("""targetUri""", """""")
            .param("""username""", "${username}")
            .param("""password""", "${password}")
            .check(status.is(200))
            .check(regex("""<title>Project Details</title>"""))
      )
    .pause(2)
    .exec(http("userLogin updateLastPageLoad")
          .post("/tdstm/userLogin/updateLastPageLoad")
          .headers(headers_4)
          .param("""url""", """/tdstm/project/show""")
          .check(status.is(200))  
          .check(bodyString.is("SUCCESS"))
      )
    .pause(8)
    .exec(http("application/list")
          .get("/tdstm/application/list")
          .check(status.is(200))
          .check(regex("""<title>Application list</title>"""))
      )
    .pause(961 milliseconds)
    .exec(http("updateLastPageLoad_2")
          .post("/tdstm/userLogin/updateLastPageLoad")
          .headers(headers_4)
          .param("""url""", """/tdstm/application/list""")
          .check(status.is(200))
          .check(bodyString.is("SUCCESS"))
      )
    .pause(194 milliseconds)
    .exec(http("application/listJson")
          .get("/tdstm/application/listJson")
          .headers(headers_7)
          .queryParam("""assetName""", """""")
          .queryParam("""validation""", """""")
          .queryParam("""moveBundle""", """""")
          .queryParam("""latencys""", """""")
          .queryParam("""runbook""", """""")
          .queryParam("""sidx""", """assetName""")
          .queryParam("""validationFilter""", """""")
          .queryParam("""rows""", """100""")
          .queryParam("""sord""", """asc""")
          .queryParam("""moveBundleId""", """""")
          .queryParam("""plannedStatus""", """""")
          .queryParam("""page""", """1""")
          .queryParam("""nd""", """1399906539610""")
          .queryParam("""event""", """""")
          .queryParam("""planStatus""", """""")
          .queryParam("""filter""", """""")
          .queryParam("""_search""", """false""")
          .queryParam("""sme""", """""")
          .queryParam("""toValidate""", """""")
          .check(status.is(200))
      )
    .pause(293 milliseconds)
    .exec(http("application/listJson_2")
          .get("/tdstm/application/listJson")
          .headers(headers_7)
          .queryParam("""latencys""", """""")
          .queryParam("""runbook""", """""")
          .queryParam("""sidx""", """assetName""")
          .queryParam("""validationFilter""", """""")
          .queryParam("""rows""", """100""")
          .queryParam("""moveBundleId""", """""")
          .queryParam("""sord""", """asc""")
          .queryParam("""plannedStatus""", """""")
          .queryParam("""page""", """1""")
          .queryParam("""nd""", """1399906540163""")
          .queryParam("""filter""", """""")
          .queryParam("""toValidate""", """""")
          .queryParam("""_search""", """false""")
          .check(status.is(200))
      )
    .pause(10)
    .exec(http("singOut")
          .get("/tdstm/auth/signOut")
          .check(status.is(200))
          .check(regex("""<title>Login</title>"""))
      )
}