package assetLists

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._
import Headers._

object GetListApp {

  val scn = scenario("get app List")
    .exec(http("App login")
      .get("/tdstm/auth/login")
      .check(status.is(200))
      .check(regex("""<title>Login</title>"""))
     )
    .pause(266 milliseconds)
    .exec(http("build.txt")
      .get("/tdstm/build.txt")
      .check(status.is(404))
     )
    .pause(5)
    .feed(csv("user_tds.csv").circular)
    .exec(http("SingIn")
        .post("/tdstm/auth/signIn")
        .headers(headers_3)
        .formParam("targetUri", "")
        .formParam("username", "${username}")
        .formParam("password", "${password}")
        .check(status.is(200))
    )
    .pause(2)
    .exec(http("userLogin updateLastPageLoad")
        .post("/tdstm/userLogin/updateLastPageLoad")
        .headers(headers_4)
        .formParam("url", "/tdstm/project/show")
        .check(status.is(200))  
        .check(bodyString.is("SUCCESS"))
      )
    .pause(8)
    .exec(http("application/list")
        .get("/tdstm/application/list")
        .check(status.is(200))
        .check(regex("<title>Application list</title>"))
    )
    .pause(961 milliseconds)
    .exec(http("updateLastPageLoad_2")
        .post("/tdstm/userLogin/updateLastPageLoad")
        .headers(headers_4)
        .formParam("url", "/tdstm/application/list")
        .check(status.is(200))
        .check(bodyString.is("SUCCESS"))
    )
    .pause(194 milliseconds)
    .exec(http("application/listJson")
        .get("/tdstm/application/listJson")
        .headers(headers_7)
        .queryParam("assetName", "")
        .queryParam("validation", "")
        .queryParam("moveBundle", "")
        .queryParam("latencys", "")
        .queryParam("runbook", "")
        .queryParam("sidx", "assetName")
        .queryParam("validationFilter", "")
        .queryParam("rows", "100")
        .queryParam("sord", "asc")
        .queryParam("moveBundleId", "")
        .queryParam("plannedStatus", "")
        .queryParam("page", "1")
        .queryParam("nd", "1399906539610")
        .queryParam("event", "")
        .queryParam("planStatus", "")
        .queryParam("filter", "")
        .queryParam("_search", "false")
        .queryParam("sme", "")
        .queryParam("toValidate", "")
        .check(status.is(200))
    )
    .pause(293 milliseconds)
    .exec(http("application/listJson_2")
        .get("/tdstm/application/listJson")
        .headers(headers_7)
        .queryParam("latencys", "")
        .queryParam("runbook", "")
        .queryParam("sidx", "assetName")
        .queryParam("validationFilter", "")
        .queryParam("rows", "100")
        .queryParam("moveBundleId", "")
        .queryParam("sord", "asc")
        .queryParam("plannedStatus", "")
        .queryParam("page", "1")
        .queryParam("nd", "1399906540163")
        .queryParam("filter", "")
        .queryParam("toValidate", "")
        .queryParam("_search", "false")
        .check(status.is(200))
    )
    .pause(10)
    .exec(http("singOut")
        .get("/tdstm/auth/signOut")
        .check(status.is(200))
        .check(regex("<title>Login</title>"))
    )
}