// automatically generated by the FlatBuffers compiler, do not modify

package net.transitionmanager.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
/**
 * "ETLInfo": {
 *     "originalFilename": "/tmp/EtlSampleData_2Z1scLRqEIg21Y5zYe5sTaAa5oqE21wo.csv"
 * },
 */
public final class FBSETLInfo extends Table {
  public static FBSETLInfo getRootAsFBSETLInfo(ByteBuffer _bb) { return getRootAsFBSETLInfo(_bb, new FBSETLInfo()); }
  public static FBSETLInfo getRootAsFBSETLInfo(ByteBuffer _bb, FBSETLInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public FBSETLInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String originalFilename() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer originalFilenameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer originalFilenameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createFBSETLInfo(FlatBufferBuilder builder,
      int originalFilenameOffset) {
    builder.startObject(1);
    FBSETLInfo.addOriginalFilename(builder, originalFilenameOffset);
    return FBSETLInfo.endFBSETLInfo(builder);
  }

  public static void startFBSETLInfo(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addOriginalFilename(FlatBufferBuilder builder, int originalFilenameOffset) { builder.addOffset(0, originalFilenameOffset, 0); }
  public static int endFBSETLInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

