// automatically generated by the FlatBuffers compiler, do not modify

package net.transitionmanager.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RowResult extends Table {
  public static RowResult getRootAsRowResult(ByteBuffer _bb) { return getRootAsRowResult(_bb, new RowResult()); }
  public static RowResult getRootAsRowResult(ByteBuffer _bb, RowResult obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public RowResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int rowNum() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int errorCount() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String domain() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer domainAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer domainInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createRowResult(FlatBufferBuilder builder,
      int rowNum,
      int errorCount,
      int domainOffset) {
    builder.startObject(3);
    RowResult.addDomain(builder, domainOffset);
    RowResult.addErrorCount(builder, errorCount);
    RowResult.addRowNum(builder, rowNum);
    return RowResult.endRowResult(builder);
  }

  public static void startRowResult(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addRowNum(FlatBufferBuilder builder, int rowNum) { builder.addInt(0, rowNum, 0); }
  public static void addErrorCount(FlatBufferBuilder builder, int errorCount) { builder.addInt(1, errorCount, 0); }
  public static void addDomain(FlatBufferBuilder builder, int domainOffset) { builder.addOffset(2, domainOffset, 0); }
  public static int endRowResult(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

