export interface IGraphNode {
	task: IGraphTask;
	successors: any[];
}

export interface IGraphTask {
	id?: number | string;
	key?: number | string;
	taskNumber?: number | string;
	label?: string;
	style?: string;
	color?: string;
	category?: string;
	fillcolor?: string;
	fontcolor?: string;
	fontsize?: string;
	status?: string;
	tooltip?: string;
	successors?: number[];
	name?: string;
	icon?: string;
	actStart?: any;
	apiAction?: any;
	apiActionCompletedAt?: string;
	apiActionInvokedAt?: string;
	apiActionSettings?: any;
	assetEntity?: IAssetEntity;
	assignedTo?: string;
	attribute?: string;
	autoGenerated?: boolean;
	comment?: string;
	commentCode?: any;
	commentKey?: string;
	commentType?: string;
	constraintTime?: any;
	constraintType?: any;
	createdBy?: any;
	dateCreated?: string;
	dateResolved?: string;
	displayOption?: string;
	dueDate?: string;
	duration?: number;
	durationLocked?: boolean;
	durationScale?: IDurationScale;
	estFinish?: string;
	estStart?: string;
	hardAssigned?: number;
	instructionsLink?: any;
	isCriticalPath?: boolean;
	isPublished?: boolean;
	lastUpdated?: string;
	moveEvent?: IMoveEvent;
	mustVerify?: number;
	notes?: any[];
	percentageComplete?: number;
	priority?: number;
	project?: IProject;
	recipe?: string;
	resolution?: string;
	resolvedBy?: string;
	role?: string;
	score?: number;
	sendNotification?: boolean;
	slack?: any;
	statusUpdated?: any;
	taskBatch?: ITaskBatch;
	taskDependencies?: ITaskDependencies[];
	taskSpec?: number;
}

interface IAssetEntity {
	id?: number;
}

interface IDurationScale {
	enumType?: string;
	name?: string;
}

interface ITaskBatch {
	id?: number;
}

interface ITaskDependencies {
	id?: number;
}

interface IProject {
	id?: number;
}

interface IMoveEvent {
	id?: number;
}
