#!/bin/bash
#help geb.allTests.run                           # Run all geb tests against both browsers

[ -e geb.allTests.log ] && rm geb.allTests.log

# Run Firefox tests
date
echo "Starting Firefox tests ..."
for i in $(seq 20)
do
    ./gradlew firefoxTest --tests specs.Cookbook.CreateRecipeSpec
done | grep 'firefoxTest
BUILD' >> geb.allTests.log

date
echo "Starting Chrome tests ..."
# Run Chrome tests
for i in $(seq 20)
do
    ./gradlew chromeTest --tests specs.Cookbook.CreateRecipeSpec
done | grep 'chromeTest
BUILD' >> geb.allTests.log

date
echo "... done."
