/*
 * Since 1.1, Grails no longer stores plugins inside your PROJECT_HOME/plugins  directory by default.
 */
grails.servlet.version = "2.5"
grails.project.class.dir = "target/classes"
grails.project.test.class.dir = "target/test-classes"
grails.project.test.reports.dir = "target/test-reports"
grails.project.plugins.dir="./plugins"
grails.project.dependency.resolver = "maven"
grails.project.source.level = 1.6
grails.project.target.level = 1.6
grails.plugin.location.'eav-model' = "./pluginscustom/eav-model-0.1"

grails.project.dependency.resolution = {
	// inherit Grails' default dependencies
	inherits("global") {
		// @TODO : JPM 1/2016 : See TM-3868
		// excludes 'itext', 'grails-plugin-log4j', 'log4j' 
		excludes 'itext'
	}
	
	log "warn" // log level of Ivy resolver, either 'error', 'warn', 'info', 'debug' or 'verbose'

	repositories {
		inherits true
		mavenRepo('http://tmdevold.tdsops.com/grails-maven')
		mavenRepo('http://repo.grails.org/grails/plugins/')
		// TODO : JPM 1/2016 : See TM-3868
		// mavenRepo('http://repo.grails.org/grails/libs-releases')
		grailsPlugins()
		grailsHome()
		grailsCentral()
		mavenLocal()
		mavenCentral()
	}

	dependencies {
		// specify dependencies here under either 'build', 'compile', 'runtime', 'test' or 'provided' scopes eg.
		runtime 'mysql:mysql-connector-java:5.1.27' 		
		compile 'com.google.guava:guava:16.0.1'
		compile 'org.apache.commons:commons-lang3:3.1'
		compile 'org.apache.poi:poi:3.7'
		build 'com.lowagie:itext:2.1.7'
		compile 'net.sf.jasperreports:jasperreports:4.5.1'
		compile 'commons-collections:commons-collections:3.2.1'
		compile 'com.canoo.webtest:webtest:3.0'
		// TODO : JPM 1/2016 : See TM-3868
		// compile "org.grails.plugins:logback:0.3.1"
	}

	plugins {
		build   ':tomcat:7.0.54'
		runtime ':resources:1.2.8'
		runtime ':hibernate:3.6.10.19'
		runtime ':database-migration:1.4.0'
		compile (":shiro:1.2.1") {
			excludes([name: 'quartz', group: 'org.opensymphony.quartz'])
		}
		//compile ':eav-model:0.1'
		compile ':filterpane:2.3.3'
		compile ':scaffolding:2.0.3'
		compile ':functional-test:1.2.7'
		compile ':jasper:1.5.3'
		compile ':jmesa:2.0.4-SNAPSHOT-0.1'
		compile ':mail:1.0.4'
		compile ':quartz:1.0.2'
		compile ':ref-code:0.3.0'
		compile ':jdbc-pool:7.0.47'
		runtime ':jquery:1.11.0.1'
		//compile ':webtest:3.0.1'
		compile ':jqgrid:3.8.0.1'
		compile ':plugin-config:0.2.0'
		compile ':jquery-ui:1.8.15'
		compile ':grails-melody:1.54.0'
	}
}

// This dependencies are generated by jasper and jmesa
grails.war.resources = { stagingDir -> 
	delete(file: "${stagingDir}/WEB-INF/lib/poi-3.0-FINAL.jar")
	delete(file: "${stagingDir}/WEB-INF/lib/poi-3.5-FINAL-20090928.jar")
	delete(file: "${stagingDir}/WEB-INF/lib/mysql-connector-java-5.1.6-bin.jar")
	delete(file: "${stagingDir}/WEB-INF/lib/commons-codec-1.3.jar")
} 

// Set runtime forking to save memory and improve performance while in development
// See the following for more information http://grails.github.io/grails-doc/2.3.x/guide/single.html#forkedMode
forkConfig = [maxMemory: 1024, minMemory: 64, debug: false, maxPerm: 256] 
grails.project.fork = [    
	test: forkConfig, // configure settings for the test-app JVM    
	run: forkConfig, // configure settings for the run-app JVM    
	war: forkConfig, // configure settings for the run-war JVM    
	console: forkConfig // configure settings for the Swing console JVM 
]

/*
 * If the application is being run locally, set the Logback configuration file
 * system property.  This is necessary as Grails will attempt to compile the .groovy
 * file instead of simply adding it to the classpath "as is".  There is a corresponding
 * event handler in 'scripts/Events.groovy' that takes care of making sure that the
 * Groovy configuration file makes it into the WAR in its un-compiled state.
 * See http://jdpgrailsdev.github.io/blog/2014/03/24/grails_logback.html
 */
// TODO : JPM 1/2016 : See TM-3868
//if(new File("${basedir}/grails-app/conf/logback.groovy").exists()) {
//    System.setProperty('logback.configurationFile', "${basedir}/grails-app/conf/logback.groovy")		
//}

